name: Cypress Tests CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Start server
        run: npm run start & # Asume que tienes un script para levantar el servidor local

      - name: Wait for server to be ready
        run: npx wait-on http://127.0.0.1:8080/index.html

      - name: Run Cypress tests
        run: npx cypress run --headless --browser chrome
